
name: .NET

permissions:
  checks: write # Required for CodeCoverageSummary
  pull-requests: write # Required for CodeCoverageSummary
  packages: write # Required for Docker
  contents: read # Required for CodeCoverageSummary 
  security-events: write # Required for Trivy

on:
  push:
    branches: 
    - main
    - feature/*
  pull_request:
    branches: [ "main" ]

jobs:

  build-dotnet-workflow:
    name: "Build application"
    permissions:
      checks: write # Required for jacoco-reporter
      pull-requests: write # Required for jacoco-reporter
      contents: read # Required for jacoco-reporter
    uses: artm-devsecops/artm-workflow-templates/.github/workflows/artm-devsecops-build-java.yml@main
    with:
      dotnet_version: 6.0.x

  build-image-workflow:
    name: "Build image"
    needs: build-dotnet-workflow
    permissions:
      packages: write # Required for Container
      security-events: write # Required for Scanning
    uses: artm-devsecops/artm-workflow-templates/.github/workflows/artm-devsecops-build-image.yml@main
    with:
      artifact_path: "./published"
      image_tag: "v1"
      image_context: "./published"
      image_files: "Dockerfile"
      container_registry: "ghcr.io"
      scan_offline: true
